# Generated by Django 4.0.2 on 2022-03-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_brend_characteristic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brend',
        ),
    ]
