# Generated by Django 4.0.2 on 2022-03-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delete_brend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'виробника',
                'verbose_name_plural': 'виробники',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brend', verbose_name='бренд товару'),
            preserve_default=False,
        ),
    ]
