# Generated by Django 4.0.2 on 2022-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_brend_product_brend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'характеристику', 'verbose_name_plural': 'характеристики'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Значення характиристики'),
        ),
    ]
