# Generated by Django 4.0.2 on 2022-03-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_characteristic_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='', upload_to='products/%Y/%m/%d', verbose_name='Основне зображення товару'),
            preserve_default=False,
        ),
    ]
