# Generated by Django 4.0.2 on 2022-03-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'додаткове зображення товару', 'verbose_name_plural': 'Додаткові зображення товару'},
        ),
    ]
