# Generated by Django 3.2.8 on 2022-03-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery1', 'Доставка до відділення Нової Пошти'), ('delivery2', "Доставка кур'єром"), ('delivery3', 'Адресна доставка кур\'єром "Нова Пошта"')], default='delivery1', max_length=50, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('pay1', 'Оплата картою'), ('pay2', 'Оплата готівкою')], default='pay1', max_length=50, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
